name: nakama1
database:
  address: [""postgresql://username:password@hostname:5432/database_name?sslmode=require""]
   # Имя базы, которое ты создавал в Railway
logger:
  level: "DEBUG"
session:
  token_expiry_sec: 7200
  encryption_key: "defaultencryptionkey"
socket:
  server_key: "defaultkey"
runtime:
  http_key: "defaulthttpkey"
  env: "production"
  # Add this to enable serving static files:
  path: "/nakama/data/modules"
  http_host: "0.0.0.0"
  http_port: 7351
console:
  address: "0.0.0.0"
  port: 7351
  username: "admin"
  password: "password"
  token_expiry_sec: 86400
metrics:
  prometheus_port: 9100