version: '3'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure --http-addr=0.0.0.0:8080 --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5

  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
    entrypoint: ["/bin/sh", "-ec"]
    command: |
      echo "Waiting for DB..." && sleep 5 && \
      /nakama/nakama migrate up --database.address root@cockroachdb:26257 && \
      exec /nakama/nakama \
        --name nakama1 \
        --database.address root@cockroachdb:26257 \
        --logger.level DEBUG \
        --session.token_expiry_sec 7200 \
        --metrics.prometheus_port 9100 \
        --runtime.path /nakama/data/modules
    restart: "no"
    depends_on:
      cockroachdb:
        condition: service_healthy
      prometheus:
        condition: service_started
    volumes:
      - ./modules:/nakama/data/modules
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
      - "9100:9100"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

volumes:
  data:
